export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SET_ERRORS = "SET_ERRORS";
export const FETCH_CHANNELS = "FETCH_CHANNELS";
export const FETCH_CHANNEL_DETAIL = "FETCH_CHANNEL_DETAIL";
export const FETCH_CHANNEL_DETAIL_LATEST = "FETCH_CHANNEL_LATEST";
export const SEND_MESSAGE = "SEND_MESSAGE";
export const SET_MESSAGES_LOADING = "SET_MESSAGES_LOADING";
export const SET_CHANNELS_LOADING = "SET_CHANNELS_LOADING";
